kind: pipeline
type: docker
name: deploy-to-test

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: build
    image: node:18
    commands:
      - npm ci
      - npm run build -- --mode test
    when:
      status:
        - success

  - name: deploy-to-test
    image: alpine
    depends_on:
      - build
    environment:
      NAS_SSH_KEY:
        from_secret: maniacbox
    commands:
      - apk add --no-cache openssh
      - mkdir -p ~/.ssh
      - echo "$NAS_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan -H maniacbox.synology.me >> ~/.ssh/known_hosts
      - ssh -i ~/.ssh/id_rsa mvogtherr@maniacbox.synology.me "mkdir -p /var/services/web/${DRONE_REPO_NAME}"
      - scp -r dist/. mvogtherr@maniacbox.synology.me:/web/${DRONE_REPO_NAME}
